"""
Shared Data Models for A2A and MCP Communication
================================================
Defines all Pydantic models used across the multi-agent system.
"""

from pydantic import BaseModel, Field
from typing import Literal
import uuid


# ============================================================================
# RAW SENSOR DATA (Internal formats unique to each Agent)
# ============================================================================

class RadarData(BaseModel):
    """Agent 1 format: Polar coordinates from radar sensor"""
    range_meters: float = Field(..., description="Target range in meters")
    azimuth_degrees: float = Field(..., description="Target azimuth angle in degrees")
    
    class Config:
        json_schema_extra = {
            "example": {
                "range_meters": 1500.0,
                "azimuth_degrees": 45.0
            }
        }


class VisualData(BaseModel):
    """Agent 2 format: Classification and certainty from visual sensor"""
    classification: Literal["drone", "aircraft", "vessel", "unknown"] = Field(
        ..., description="Target classification type"
    )
    certainty_percent: int = Field(
        ..., ge=0, le=100, description="Classification certainty (0-100%)"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "classification": "drone",
                "certainty_percent": 95
            }
        }


# ============================================================================
# NORMALIZED DATA (Standardized output from MCP Tool)
# ============================================================================

class NormalizedTarget(BaseModel):
    """Standardized target format after MCP normalization"""
    x_pos: float = Field(..., description="Normalized X coordinate")
    y_pos: float = Field(..., description="Normalized Y coordinate")
    target_type: str = Field(..., description="Standardized target classification")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Normalized confidence (0.0-1.0)")
    
    class Config:
        json_schema_extra = {
            "example": {
                "x_pos": 750.0,
                "y_pos": 1050.0,
                "target_type": "DRONE",
                "confidence": 0.95
            }
        }


# ============================================================================
# A2A PROTOCOL DATA STRUCTURES
# ============================================================================

class A2ATask(BaseModel):
    """A2A Task sent from Fusion Agent (Client) to Sensor Agents (Servers)"""
    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sector_id: str = Field(..., description="Surveillance sector identifier")
    request_type: str = Field(default="track", description="Type of request")
    
    class Config:
        json_schema_extra = {
            "example": {
                "task_id": "550e8400-e29b-41d4-a716-446655440000",
                "sector_id": "Alpha Sector",
                "request_type": "track"
            }
        }


class A2AArtifact(BaseModel):
    """Final structured A2A Artifact (Report) generated by Fusion Agent"""
    fusion_id: str = Field(..., description="Unique fusion report identifier")
    targets: list[NormalizedTarget] = Field(..., description="List of normalized targets")
    summary: str = Field(..., description="Human-readable summary of fusion results")
    
    class Config:
        json_schema_extra = {
            "example": {
                "fusion_id": "RPT-12345678",
                "targets": [{
                    "x_pos": 750.0,
                    "y_pos": 1050.0,
                    "target_type": "DRONE",
                    "confidence": 0.95
                }],
                "summary": "Track successful for Sector Alpha. Found 1 target."
            }
        }